### ISSUE TITLE
这个图片格式支持gif吗？

### ISSUE THREAD

**Issue by Sihnbaobao** [Twiyin0/koishi-plugin-youpokedme#3]
图片我是能正常发送的，只不过好像没看见有发gif，然后又新建个文件夹丢了gif进去试了试，但发现好像都不行，日志没有报错，是不支持吗？
![image](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/140788757/bc4dfb56-37f2-403a-b8ab-a18b70f1aad5)

**Comment by Twiyin0** [comment]
支持gif的你得文件名格式不对
![image](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/87588281/16c31849-2b5c-42f8-b3bd-3e573f57834c)
如果是gif应该是 `file:///C:/user/photos/awa.gif` 这样

**Comment by Twiyin0** [comment]
是的，对文件夹扫描的时候我没有扫描gif文件，感谢反馈，这两天会更新

**Comment by Twiyin0** [comment]
已发布更新，请将插件更新至v1.1.1

**Comment by Twiyin0** [comment]
先关掉这个issues啦，有问题再开新的吧
