### ISSUE TITLE
更新koishi后插件失灵

### ISSUE THREAD

**Issue by d2033801** [Twiyin0/koishi-plugin-youpokedme#4]
![图片](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/70478207/c2475e58-42da-440e-8601-0fb7ed34af6b)
上方这里印象中应该有个绿的什么东西但是并没有出现，而且戳一戳也没反应
![图片](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/70478207/4c117388-d21e-437a-a257-3fde5828c3e8)
这是koishi版本，插件版本也为最新1.1.1
不晓得具体什么原因，甚至重置过koishi、删除koishi.db文件也没用

**Comment by d2033801** [comment]
![图片](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/70478207/fc4046ad-27f5-4728-a540-52330f04b65b)
今天尝试用新实例，初次下载后弹出了这样的报错信息，不知是否有关联

**Comment by Twiyin0** [comment]
- 1. red协议、超时空猫猫适配器目前不支持戳一戳，目前QQ能使用戳一戳的只有go-cqhttp的Android、Android Pad与aPad协议
- 2. 初次启动需要填写必须配置项reply
初次启动实例需要填写必须项reply，把reply的内容填写后才能使用

**Comment by Twiyin0** [comment]
后续询问请提供以下详细信息：
- 1. 使用的协议（适配器）；
- 2. 无法触发戳一戳时的配置项以及具体log
以便我分析哪里出问题了

**Comment by d2033801** [comment]
感谢您的回复！如我主贴的图所示，reply项是配置了的

- 这是使用的第三方gocqhttp与qsign
![图片](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/70478207/90547aeb-4fa3-4118-b2bd-37d3f7f4cfaa)
![图片](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/70478207/4e180aed-f7a0-45d0-98d5-195ae922f034)

- 这是配置项
![图片](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/70478207/828611bc-54fe-4ff7-b709-3508d1bc215d)

- 使用qdvc导出的的安卓手机协议
![图片](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/70478207/c4301a6d-b2c3-4c4f-a6d3-c34bf73d0ab6)

- 日志的话这个第三方qsign的日志比较奇特，我也不知道怎么正常配置，看不太懂
![图片](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/70478207/02eb11c6-a232-47ae-bbe3-fe2f6c14e598)

- 出错时间大约在十月五号，koishi更新4.15.0之后，在那之前都能正常用，出问题的更新前后除了更新依赖以外未加装任何新插件。
- 另外，我在koishi论坛发现不止我且不止您的戳一戳相关插件出现了这个问题[bot收到了戳一戳消息但做不出回应](https://forum.koishi.xyz/t/topic/5396)，尚不清楚问题究竟是出现在哪里

**Comment by Twiyin0** [comment]
![image](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/87588281/b82ca29e-8b5f-45a5-81cd-769803ea9152)  
梦梦说4.15.x进行了协议层的破坏性变更，可能是这个导致插件无法获取到戳一戳消息，可以尝试降级回4.14.x

**Comment by Twiyin0** [comment]
后面细看了下文档  
![image](https://github.com/Twiyin0/koishi-plugin-youpokedme/assets/87588281/51dec408-0520-4ce5-8f18-0d86700914df)
由于go-chttp已经停止支持所以我不打算继续维护，如果感兴趣可以clone我的项目进行修改

**Comment by d2033801** [comment]
这样吗😭😭太遗憾了，感谢您插件之前带来的帮助
